package com.sundy.iman.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sundy.iman.greendao.ImUserInfo;

import com.sundy.iman.greendao.ImUserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig imUserInfoDaoConfig;

    private final ImUserInfoDao imUserInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        imUserInfoDaoConfig = daoConfigMap.get(ImUserInfoDao.class).clone();
        imUserInfoDaoConfig.initIdentityScope(type);

        imUserInfoDao = new ImUserInfoDao(imUserInfoDaoConfig, this);

        registerDao(ImUserInfo.class, imUserInfoDao);
    }
    
    public void clear() {
        imUserInfoDaoConfig.clearIdentityScope();
    }

    public ImUserInfoDao getImUserInfoDao() {
        return imUserInfoDao;
    }

}
